version: '3'

services:
  bitpin:
    build: .
    command: gunicorn Bitpin_core.wsgi:application --bind=0.0.0.0:8000 --log-level=debug
    volumes:
      - .:/my_app_dir
    ports:
      - "8006:8000"
    networks:
      - network
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
        - ./volume-mariadb:/var/lib/mysql
    networks:
        - network
    # ports:
        # - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456789987654321

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - network
    ports:
      - "8188:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    links:
      - mariadb

networks:
    network:
        driver: bridge
